# Generated by Django 5.2.7 on 2025-10-02 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookauthor',
            name='author_id',
        ),
        migrations.RemoveField(
            model_name='bookreview',
            name='book_id',
        ),
        migrations.RemoveField(
            model_name='bookauthor',
            name='book_id',
        ),
        migrations.RemoveField(
            model_name='bookreview',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookAuthor',
        ),
        migrations.DeleteModel(
            name='BookReview',
        ),
    ]
