# Generated by Django 5.2.7 on 2025-10-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatars',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
